version: '3.2'

services:
   a:
    image: m3c1994/web1:1.0
    environment:
      VIRTUAL_HOST: antonio-paya.test
    restart: always    
   b:
    image: m3c1994/web2:1.0
    environment:
     VIRTUAL_HOST:  network-soluciones.test
    restart: always    
   c:
    image: m3c1994/web3:1.0
    environment:
      VIRTUAL_HOST:  example-page.test
    restart: always
    
   d:
    image: m3c1994/web4:1.0
    links:
     - db
    environment:
      VIRTUAL_HOST: short.test
    ports: 
      - "5000:5000"
    restart: "always" 
    
   e:
    image: m3c1994/web5:2.0
    links: 
     - db
    environment:
      VIRTUAL_HOST: pos.test
    restart: "always" 
    
   nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    privileged: true

   db:
      image: m3c1994/web6:2.0
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: sistemas

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8181:80'
      environment:
        PMA_HOST: db
        VIRTUAL_HOST: phpmyadmin.test
    
    
